"""Build the expanded database and offline Lua assets from reviewed source data."""
import json
import re
import unicodedata
from pathlib import Path
from build_demo_data import build_rules, build_corpus, build_kaomoji

ROOT = Path(__file__).resolve().parents[1]

def lua(value):
    if isinstance(value, dict):
        return "{" + ",".join("[" + lua(k) + "]=" + lua(v) for k, v in value.items()) + "}"
    if isinstance(value, list):
        return "{" + ",".join(map(lua, value)) + "}"
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(value, ensure_ascii=False)

def build():
    build_rules()
    build_corpus()
    build_kaomoji()
    read = lambda name: json.loads((ROOT / "data" / name).read_text(encoding="utf-8"))
    lexicon = read("lexicon.json")
    aliases = dict(cat="猫", dog="狗", rabbit="兔", bear="熊", pig="猪", bird="鸟", fish="鱼", tea="茶", flower="花", money="钱", sleep="睡", eat="吃", run="跑")
    for topic in lexicon["topics"]:
        topic["exact"] = [aliases[topic["id"]]] if topic["id"] in aliases else []
    for phrase, emotion in [("哭", "crying"), ("笑", "amused"), ("酷", "smug"), ("苦", "sad")]:
        lexicon["rules"].append(dict(id="exact_" + emotion, phrases=[phrase], match="exact", emotions={emotion:.9}, intent="neutral"))
    original = read("rules.json")
    for rule in lexicon["rules"]:
        rule["pattern"] = "|".join(re.escape(p) for p in sorted(rule["phrases"], key=len, reverse=True))
    merged = dict(version=2, rules=original["rules"] + lexicon["rules"], topics=lexicon["topics"])
    entries = read("kaomoji.json")
    normalize = lambda text: "".join(unicodedata.normalize("NFKC", text).split())
    seen = {normalize(e["text"]) for e in entries}
    kinds = {t["id"]:t["kind"] for t in lexicon["topics"]}
    for group in read("collections.json"):
        for text in group["texts"]:
            if normalize(text) in seen:
                continue
            seen.add(normalize(text))
            topics = group.get("topics", [])
            entries.append(dict(text=text, family=group["family"], topics=topics,
                category=kinds[topics[0]] if topics else "emotion", emotions=group["emotions"],
                intents=group.get("intents", ["neutral"]), tones=group.get("tones", ["informal"]),
                tags=group.get("tags", []), intensity=group.get("intensity", .5)))
    for name, value in [("rules.json", merged), ("kaomoji.json", entries)]:
        (ROOT / "data" / name).write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (ROOT / "rime/kaomoji_data.lua").write_text("-- Generated by scripts/build_offline.py; edit data sources.\nreturn " + lua(dict(rules=lexicon["rules"], topics=lexicon["topics"], entries=entries)) + "\n", encoding="utf-8")
    print(f"Built {len(entries)} unique kaomoji, {len(lexicon['topics'])} topics, {sum(len(r['phrases']) for r in lexicon['rules'])} emotion phrases")

if __name__ == "__main__":
    build()
